version: "3"
services:
  api:
    restart: always
    build: .
    ports:
      - "80:80"
    environment:
      - GIN_MODE=release
    depends_on:
      - db
    links:
      - "db:db"
  db:
    image: postgres:alpine
    env_file: .env
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080


